config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :sessions,   only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'  
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  

  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end
  
  def about
  end
  
  def contact
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Me') %>
<h1>About Me</h1>
<h2>My Class</h2>
<body>
  I offer private English classes for all levels and age groups.  I teach
  everything from Business English all the way down to Beginner's English.
  I offer hands on teaching with an emphasis in conversational skills, but
  can obviously cater to your specific needs.  I present and teach in person
  but like to share materials online.  This website helps with that but for
  full access to materials an email account or dropbox account is preferred.
</body>
<h2>My Credentials</h2>
<body>
  - TEFL certified <br>
  - BS in Industrial Engineering from <a href="https://www.mst.edu">Missouri University of Science & Technology</a> <br>    
  - 2 Years as an Industrial Engineer for <a href="http://www.ford.com">Ford Motor Company</a> <br> 
  - Previous engineering/management roles - <a href="http://www.utc.com">UTC</a>, <a href="http://www.packaging-services.com">Span Packaging</a>, and 
  <a href="http://www.asi.com">Automatic Systems Inc</a><br> 
  - Teaching professionally since December 2013

<body>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<h2>
  email - <a href="mailto:shorty2426@gmail.com">Scott Kalwei</a>.<br> 
  czech phone - +420-731-976-842<br> 
  skype - scott.kalwei1 <br> 
  <a href="https://www.facebook.com/scott.kalwei">Facebook</a> <br> 
  <a href="http://www.linkedin.com/pub/scott-kalwei/18/aba/64b">Linkedin</a> <br> 
  <a href="http://scottkalwei.wordpress.com/">My Blog</a> <br>
 </h2>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Thanks for visiting my website!  If your interested in getting information
  about a class please <%=link_to "Sign up", signup_path%> and write a message.  If you prefer, you can just send me
  an email at <a href="mailto:shorty2426@gmail.com">Scott Kalwei</a>.  Easy as that :).  <%=link_to "Contact Page", contact_path%> holds all my
  contact information.  If you want more information then click on <%=link_to "About", about_path%> and read my credentials.
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>    
      
      <section>
        <%= render 'shared/stats' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
     
    </aside>
    
    <div class="span8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
  
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to Scott Kalwei's English Teaching</h1>

    <h2>
      Do you want to learn English?  <%=link_to "Sign up", signup_path%> and get enrolled and participate in my hands on
      and online interactive classes!  Want to learn more?  Click <%=link_to "About", about_path%> and see what I offer
      and my credentials.  Want another way to contact me?  Click on my <%=link_to "Contact Page", contact_path%>.<br>     
      Thanks! I look forward to working with you.
    </h2>

    <%= link_to "Sign up now!", signup_path,
                                class: "btn btn-large btn-primary" %>
  </div>
<% end %>